version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services: 
  db: 
    image: postgres:9.6
    volumes: 
      # Volumes dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
    # Site
      - ./web:/usr/share/nginx/html/
    # Configuração do proxy revero
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes: 
    # Aplicação
    - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment:
      - DB_NAME=abc_email_sender
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
  # Build procura o Dockerfile na pasta worker
    build: worker
    volumes:
    # Worker
      - ./worker:/worker
    working_dir: /worker
    # Remove o bash porque já está sendo feito no Dockerfile
    # Command está sendo passado como parametro para o entrypoint no Dockerfile
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue